tap "atlassian/tap"
tap "federico-terzi/espanso"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "stephan-hesselmann-by/blueyonder"
tap "ul/kak-lsp"
tap "zegervdv/zathura"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# C++ library for C++/Python3 interoperability
brew "boost-python3"
# Powerful command-line bookmark manager
brew "buku"
# Fuzzy matcher that uses std{in,out} and a native GUI
brew "choose-gui"
# Console Matrix
brew "cmatrix"
# GNU File, Shell, and Text utilities
brew "coreutils"
# GNU compiler collection
brew "gcc"
# Render markdown on the CLI
brew "glow"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Next-gen compiler infrastructure
brew "llvm"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Terminal multiplexer
brew "tmux"
# URL extractor/launcher
brew "urlview"
# Enhances tmux's to provide multiuser terminal multiplexing
brew "wemux"
# Homebrew, but with Docker images
brew "whalebrew"
brew "atlassian/tap/atlassian-plugin-sdk"
# Cross-platform Text Expander written in Rust
brew "federico-terzi/espanso/espanso"
# Convert CSV to Blue Yonder Supply & Demand API compatible XML
brew "stephan-hesselmann-by/blueyonder/di-csv2xml"
cask "amethyst"
cask "app-cleaner"
cask "clipy"
cask "dbeaver-community"
cask "docker"
cask "eloston-chromium"
cask "firefox"
cask "font-firacode-nerd-font"
cask "karabiner-elements"
cask "keepassxc"
cask "microsoft-azure-storage-explorer"
cask "mumble"
cask "omnigraffle"
cask "pycharm"
cask "rectangle"
cask "ukelele"
cask "visual-studio-code"
cask "zoomus"
whalebrew "whalebrew/whalesay"
