keys:
  - &master age14hq2vn8nalmp9plfn4x6x9haxm3dv0jzv2mdx2f8p4ud2xwcdq0sfst6p8
  - &redhat age1tpkeasesjvhrnptlpt2ndst9ytz4xe6xkrav76pstykmxv6lq9pq9ex6p3
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *master
          - *redhat
