#!/usr/bin/env sh

/home/stephan/.config/polybar/launch.sh

bspc monitor -d term code web media other

bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         0
bspc config bottom_padding      0

bspc config normal_border_color '#0C1115'
bspc config active_border_color '#0C1115'
bspc config focused_border_color '#928374'

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a firefox desktop='^3' follow=on
bspc rule -a '*:zathura' state=tiled
