set -g theme_display_git no
set -g theme_use_abbreviated_branch_name no
set -g theme_display_docker_machine yes
set -g theme_display_virtualenv yes
set -g theme_display_user ssh
set -g theme_display_hostname ssh
set -g theme_display_cmd_duration yes
set -g theme_nerd_fonts no
set -g theme_powerline_fonts no
set -g theme_title_display_process yes
set -g theme_title_display_path no
set -g theme_title_display_user yes
set -g theme_title_use_abbreviated_path yes
set -g theme_display_date no
set -g theme_avoid_ambiguous_glyphs yes
set -g theme_show_exit_status yes
set -g theme_display_jobs_verbose yes
set -g default_user your_normal_user
set -g theme_color_scheme dark
set -g fish_prompt_pwd_dir_length 0
set -g theme_project_dir_length 0
set -g theme_newline_cursor yes
set -g theme_newline_prompt '❯ '
