#!/usr/bin/env sh

sudo modprobe -r psmouse
sudo modprobe psmouse
picom --daemon
feh --bg-max --randomize ~/Dropbox/backgrounds/*
sxhkd -c ~/.config/sxhkd/sxhkdrc &
xset r rate 300 60 &
dunst &
unclutter &
udiskie -s &
nm-applet &

setxkbmap -option caps:escape

[ ! -f ~/.config/shortcutrc ] && shortcuts >/dev/null 2>&1
