#!/usr/bin/env sh

sudo modprobe -r psmouse
sudo modprobe psmouse
picom --daemon
feh --bg-max --randomize ~/Dropbox/backgrounds/*
sxhkd -c ~/.config/sxhkd/sxhkdrc &
xset r rate 300 60 &
dunst &
unclutter &
udiskie -s &
nm-applet &

systemctl --user start syncthingtray.service

setxkbmap -option caps:escape
