version: 2
root-markers:
  - .git/

provide-definition: true

tools:
  black: &black
    format-command: "black -"
    format-stdin: true

  eslint: &eslint
    lint-command: "eslint -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true

  flake8: &flake8
    lint-command: "flake8 --max-line-length 160 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "flake8: %f:%l:%c: %m"

  golint: &golint
    lint-command: "golint"
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m"

  goimports: &goimports
    format-command: "goimports"
    format-stdin: true

  isort: &isort
    format-command: "isort --stdout -"
    format-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: "lua-format -i"
    format-stdin: true

  mypy: &mypy
    lint-command: "mypy --show-column-numbers --ignore-missing-imports"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  prettier: &prettier
    format-command: "prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}"

  terraform: &terraform
    format-command: "terraform fmt -"
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "shellcheck: %f:%l:%c: %trror: %m"
      - "shellcheck: %f:%l:%c: %tarning: %m"
      - "shellcheck: %f:%l:%c: %tote: %m"

  vim-vint: &vim-vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  css:
    - <<: *prettier
  go:
    - <<: *goimports
    - <<: *golint
  html:
    - <<: *prettier
  lua:
    - <<: *lua-lua-format
  javascript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  json:
    - <<: *prettier
  markdown:
    - <<: *prettier
  python:
    - <<: *black
    - <<: *isort
  scss:
    - <<: *prettier
  sh:
    - <<: *shellcheck
  tf:
    - <<: *terraform
  typescript:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  vim:
    - <<: *vim-vint
  yaml:
    - <<: *prettier
