version: 2
root-markers:
  - .git/
  - .root

provide-definition: true

tools:
  black: &black
    format-command: "black --quiet -"
    format-stdin: true

  eslint: &eslint
    lint-command: "eslint -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true

  flake8: &flake8
    lint-command: "flake8 --max-line-length 160 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  golint: &golint
    lint-command: "golint"
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m"

  goimports: &goimports
    format-command: "goimports"
    format-stdin: true

  hadolint: &hadolint
    lint-command: "hadolint"
    lint-formats:
      - "%f:%l %m"

  isort: &isort
    format-command: "isort --quiet -"
    format-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: "lua-format --config=$HOME/.config/luaformatter/config.yaml -i"
    format-stdin: true

  pandoc-rst: &pandoc-rst
    format-command: "pandoc -f rst -t rst -s --columns=90"
    format-stdin: true

  pgformatter: &pgformatter
    format-command: "pg_format -"
    format-stdin: true

  prettier: &prettier
    format-command: "prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}"

  rst-lint: &rst-lint
    lint-command: "rst-lint --encoding utf-8 --level warning --format text ${INPUT}"
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%t%*[A-Z] %f:%l %m"

  shellcheck: &shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  shfmt: &shfmt
    format-command: "shfmt -ln bash -i 2 -bn -ci -sr -kp"
    format-stdin: true

  spectral: &spectral
    lint-command: "spectral lint --format=text ${INPUT}"
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c %trror %m"
      - "%f:%l:%c %tarning %m"
      - "%f:%l:%c %tnfo %m"

  terraform: &terraform
    format-command: "terraform fmt -"
    format-stdin: true

  vale: &vale
    lint-command: "vale --config=$HOME/.config/vale/vale.ini --relative --output=line ${INPUT}"
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c:%*[^:]:%m"

  vint: &vint
    lint-command: "vint --enable-neovim --style-problem --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  # asciidoctor:
  #   - <<: *vale
  css:
    - <<: *prettier
  dockerfile:
    - <<: *hadolint
  go:
    - <<: *goimports
    - <<: *golint
  # help:
  #   - <<: *vale
  html:
    - <<: *prettier
  lua:
    - <<: *lua-lua-format
  javascript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  json:
    - <<: *prettier
    - <<: *spectral
  jsonc:
    - <<: *prettier
    - <<: *spectral
  markdown:
    - <<: *prettier
    # - <<: *vale
  # python:
  #   - <<: *black
  #   - <<: *isort
  rst:
    - <<: *rst-lint
    - <<: *pandoc-rst
    # - <<: *vale
  scss:
    - <<: *prettier
  sh:
    - <<: *shellcheck
    - <<: *shfmt
  sql:
    - <<: *pgformatter
  # text:
  #   - <<: *vale
  tf:
    - <<: *terraform
  typescript:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  vim:
    - <<: *vint
  yaml:
    - <<: *prettier
