#!/usr/bin/env sh

SC_DEPLOY_HOME=${HOME}/git/sc-deploy
fd 	. ${SC_DEPLOY_HOME}/deploy/projects \
	--extension=ini \
	--exec-batch realpath --relative-to="${SC_DEPLOY_HOME}/deploy" \
| fzf \
| xargs ~/git/sc-deploy/deploy/sc-deploy-client.sh credentials -i
