#!/usr/bin/env python
import argparse
import re
from urllib.parse import unquote


def main():
    parser = argparse.ArgumentParser(description="Convert hazure url to azure sas url.")
    parser.add_argument(
        "hazure", type=str, help="Hazure url string.",
    )
    args = parser.parse_args()

    match = re.search(
        ("hazure://(?P<account_name>[^:]+):(?P<sas>[^@]+)@(?P<container>[^?]+)?"),
        args.hazure,
    )
    account_name = match.group("account_name")
    container = match.group("container")
    sas = unquote(match.group("sas"))

    print(f"https://{account_name}.blob.core.windows.net/{container}?{sas}")


if __name__ == "__main__":
    main()
